# Write a program to input eight numbers from the user and display all the unique numbers (once)
s = set() 

user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 
s.add(int(user))
user = input("Enter number: ") 

print(s)